### ISSUE TITLE
redux/lesson2/segment2:Create Actions: 3rd video: Reference to the

### ISSUE THREAD

**Issue by zhangtreefish** [udacity/reactnd-issues#110]
Same as As ticket #88. Since it is closed, I am posting it as a new issue:
A student posted in LH: ''m watching Redux Lesson2 /2 Create Actions last video... It starts "If you remember back to the final project"... and starting UdaciMeals project... Can I have some idea about the project? Am I missing video explaining of UdaciMeals ?'.

**Comment by hbkwong** [comment]
Hey @zhangtreefish, I'll check in with our production team tomorrow to remedy this on Monday. To be frank, I don't agree with the phrase "final project" since it implies that it's somehow already built. We're just _starting_ to build that project in this Lesson!

In the meantime, I'll add a text disclaimer for the video to avoid further confusion. With or without that phrase, the rest of the content in the video should go unchanged.

**Comment by hbkwong** [comment]
The new verbiage is live, but I'm still going to get another update in place this week. Thank you for the chat on Slack earlier too 👍

**Comment by hbkwong** [comment]
All good to go. The misleading phrase has been removed @zhangtreefish
