### ISSUE TITLE
Create Reducers quiz passes with incorrect answer

### ISSUE THREAD

**Issue by sarah-maris** [udacity/reactnd-issues#122]
I did not look at the quiz closely and solved it completely wrong -- but my code still passed!
https://classroom.udacity.com/nanodegrees/nd019/parts/7b1b9b53-cd0c-49c9-ae6d-7d03d020d672/modules/c278315d-f6bd-4108-a4a6-139991a50314/lessons/782f801d-3bd8-4b2b-b788-608b0fbe1306/concepts/7dfc2204-c9e1-4c68-bf05-d6ba820b4ba8

**Comment by sarah-maris** [comment]
yep it's completely wrong...

```
const appReducer = (state, action) => {
  if (action.type === 'DELETE_FLAVOR' ) {
      var newState = state;
      state.map( (item)  =>  item.flavor === action.flavor ?  item.flavor-- : item.flavor )
      return  newState;
  } else return state;
}
```

But it did pass. 

![image](https://user-images.githubusercontent.com/6298143/29251633-55a43550-8026-11e7-9da8-9a23e4b2a8e4.png)

**Comment by hbkwong** [comment]
Hey sarah-maris, good call! To be frank, this is the first time I've seen this solution from our students! Were you still able to edit this to a "correct" solution? I've since filed a JIRA ticket to keep this on our radar, but feel free to Slack me directly if you still run into issues. Thank you for checking in with this!
