### ISSUE TITLE
Suggestion from reviewers to use react-key-index

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#128]
For the MyReads project, many students have received feedback to look into the use of react-key-index package; as the book.id property might not be truly unique.

Several people mention in Slack that the package is troublesome. I have experienced some odd behaviour as well. The package seems to be obsolete as the Github page no longer exists. Is it proper to still recommend this package?

Thanks for the consideration.

**Comment by hbkwong** [comment]
Hey breakpoint25, thanks for giving me the heads up. Personally speaking, the source code being (now-) unavailable is a good indicator to me that support no longer really exists for the package. There are other ways of making sure keys are unique. If you run into dups, let me know! Removing those dups should make things run more smoothly (rather than "forcing" uniqueness). Have a great weekend!

**Comment by breakpoint25** [comment]
I will try the keywords and let you know if I find any.

There were good suggestions of also youing the map/filter methods to find and remove any beforehand.

Also someone mentioned using the lodash package which has a uniqBy method which can also be useful.
