### ISSUE TITLE
ES6 - Lesson 1 - Section 5 - Quiz: Build an HTML Fragment (1-2)

### ISSUE THREAD

**Issue by breakpoint25** [udacity/reactnd-issues#130]
There is a link for Animal Trading Cards which leads to a Discussion Forum web page that say "Sorry, you don't have access to that topic!"

**Comment by breakpoint25** [comment]
Section 15 (...Rest Parameters) also has a link at the bottom for "for...of loop." which doesn't load saying we aren't allowed access.

https://classroom.udacity.com/nanodegrees/nd016/parts/11a45d59-bb81-44a9-be76-042c99e5f051/modules/cbf6deb8-d2cc-4757-b3a9-a1c58a4acd82/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/f1955923-744a-4906-8f64-1ddcb34c6da2#

**Comment by hbkwong** [comment]
Hey @breakpoint25, I've since removed that link from the page since it goes to the forum for the Front-End Web Developer Nanodegree program. That is, students in the ES6 course are not necessarily enrolled in FEND. 

If you're enrolled in that program and still see restricted access to the forums, let me know and I'll get you in ASAP. Thanks for reporting this!
