### ISSUE TITLE
React Fundamentals L1-S4 Q2 Wrong answer

### ISSUE THREAD

**Issue by fediev** [udacity/reactnd-issues#141]
I think Q2's answer should be just 'FlightPlanner', but current correct answer is 'FlightPlanner' and 'LocationPicker'

**Comment by hbkwong** [comment]
Hi @fediev, `LocationPicker` owns the data for `OriginPicker` and `DestinationPicker`, since those two are child components of `LocationPicker`.

**Comment by fediev** [comment]
What 'data' means in this context is not so clear, so I'm not sure about my opinion. But, when only 'FlightPlanner' is selected, feedback message says like this.

 ' Because `LocationPicker` is a parent component, it would make sense that it would handle all changes for its child components. But because it is also a child component, it would also need to send up'

I think this explanation means only `FlightPlanner` is right answer, but evaluation is conflict with this.

**Comment by hbkwong** [comment]
Hi fediev, if `LocationPicker` is not selected, that feedback ("Because `LocationPicker`...") is displayed.  If `FlightPlanner` is not selected, feedback should say:

```
Since `FlightPlanner` is the parent component and stores all of the flight data, any changes to the data should be made by this component. 
```

This is the first I've heard of it since the course has been online, but I'll still go ahead and update the `LocationPicker`'s suggestion to clear up any confusion. Thanks for checking in! You are welcome to Slack me directly too if you run into issues.
