### ISSUE TITLE
Redux 2.3: Stack trace

### ISSUE THREAD

**Issue by becomeLegend** [udacity/reactnd-issues#157]
I'm getting the following stack trace when I submit my AppReducer code in Redux 2.3:

Traceback (most recent call last):
  File "falcon.py", line 96, in 
    sys.stdout.write(formatter.format_results_as_json_string(mode_idx, stack_module.submit_files(), args.show_pretty_submit, stack_module.transform))
  File "/tmp/vmuser_glrgbcoker/falcon/formatter.py", line 62, in format_results_as_json_string
    results[files.RESULTS_OUT] = transformer(util.get_file_contents(files.RESULTS_OUT))
  File "falcon/stack/js_mocha.py", line 167, in transform
    grading_response = json.loads(eval_output)
  File "/usr/lib/python2.7/json/init.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by hbkwong** [comment]
Hi @becomeLegend, do you mind sharing the code that produces this?

**Comment by becomeLegend** [comment]
I think it was a variation of this code:
function appReducer ( state, action) {

    state = [
        { flavor: 'Chocolate', count: 36 },
        { flavor: 'Vanilla', count: 210 }];
    switch (action.type) {
        case 'DELETE_FLAVOR':
            return {
                ...state.filter(state => state.flavor !== 'Vanilla')
            };
    }
    return state
}

**Comment by hbkwong** [comment]
Hi becomeLegend, just wanted to check in. Maybe the formatting of the code is just off (since it wasn't submitted as a snippet), but why is the `state` being reset/hard-coded to `[ { flavor: 'Chocolate', count: 36 }, { flavor: 'Vanilla', count: 210 }]` within the reducer function? Also, I'd look into the use of the spread operator in what you shared as well (parsing error).

**Comment by becomeLegend** [comment]
Since was "work in progress" - I have solved it since then but the feedback of stack trace was not very helpful in getting to the solution. It doesn't matter what my code is doing - it should not produce a stack trace like that. This is why I didn't want to post my code to begin with - it's not about my code, it's about the back end not being able to handle it.

**Comment by hbkwong** [comment]
Hi becomeLegend, thanks for sharing. It's important to see the code so that I can reproduce the error on my end. I agree with you though; it's not a very helpful message to see after running it. I'll make sure the tests for this quiz (and others) are good to go for a future release. If you continue to see something like this, feel free to reach out (even Slack me directly)! Thanks for checking in!
