### ISSUE TITLE
React-native 2.3 video onChangeText instead of onChange?

### ISSUE THREAD

**Issue by hsjung22** [udacity/reactnd-issues#189]

**Comment by hbkwong** [comment]
Hi @hsjung22, thanks for checking in. Within 2.3, which video in particular did you see this issue in?

**Comment by hbkwong** [comment]
Hi @hsjung22, if you're referring to Tyler's video on `TextInput`, `onChangeText`should definitely be used instead of `onChange` (with the way that the event handler was written). Keep in mind that the former passes the event object as an arg, while the latter passes the actual text value as an arg. We'll have the page updated shortly!
