### ISSUE TITLE
Inconsistencies between Readable's overview and Rubric

### ISSUE THREAD

**Issue by LonelyPrincess** [udacity/reactnd-issues#216]
Some of the requeriments specified in the Readable project's overview page are missing from the project's Rubric and viceversa, which can be confusing for those who are using only one of these sources as a reference.

The requeriments specified in the overview page that are not listed in the Rubric are:

* List view pages must include a list of all the available categories. 
* Posts should appear sorted by score (highest first) by default on any of the list view pages. 
* Control for adding new post should be visible, at least, in any of the list view pages. 
* In post details page, comments should appear sorted by score (highest first). 

Also, since the Rubric is meant to be the single source of truth, including a link to it in the overview page may help students not to overlook its existence until they enter the submission page. Just having that link could be helpful to anyone starting the project now, since they'll be redirected to the Rubric from the start. 

It actually happened to me that I didn't notice there was a Rubric until today, so I wasn't aware of some of the requeriments missing in the overview. :sweat_smile:

**Comment by forbiddenvoid** [comment]
@hbkwong Is working on moving some of the instructions to the overview page so that the rubric is more visible. 

I've updated the rubric and overview page to reflect:

* The default ordering of the posts/comments isn't really that important - we're more concerned that you have the ability to control the ordering by score or timestamp. So I've removed those two from the overview page.
* The other two are valid, and definitely should be part of the rubric. I've added them to the functionality rubric point to more accurately reflect the spec we're looking for.

**Comment by hbkwong** [comment]
Thanks @forbiddenvoid! The Overview page now includes submissions instructions. And thank you @LonelyPrincess the amount of detail in your message. Let's get these roadblocks out of your way ASAP.

**Comment by LonelyPrincess** [comment]
Thanks to you both, @hbkwong and @forbiddenvoid! Keep up the good work! :smile:

I'm very happy with the course so far, so I'm glad I was able to help! If anything else comes up, I'll make sure to open another issue with any information you may need. :wink:
