### ISSUE TITLE
StatusBar customization should not be in TabNavigator page

### ISSUE THREAD

**Issue by LonelyPrincess** [udacity/reactnd-issues#221]
In lesson 4.2 there is an explanation on how to customize the status bar within React Native applications. 

That doesn't have much to do with TabNavigator or navigation as a whole, so I think it would be a better idea to move it to a new page in Lesson 3 (Styling and Layout).

**Comment by hbkwong** [comment]
Hey @LonelyPrincess, thanks for the heads up! We'll keep this in mind as we update the React Nanodegree program. It's going to be a bit more that simply moving the text and videos over to Lesson 3, since the videos include an already-complete TabNavigator that wasn't introduced in Lesson 2.

By the way, have a wonderful holiday weekend! Thanks again for all your contributions.
