### ISSUE TITLE
CreateContact should be Stateless Functional Component

### ISSUE THREAD

**Issue by SherylHohman** [udacity/reactnd-issues#227]
Lesson 5: Managing App Location with React Router

Module: 2. Dynamically Render Pages, video 2 - Module 6: Finishing the Contact Form 

Commit where `<CreateContact/>` is first defined:  
commit: https://github.com/udacity/reactnd-contacts-complete/commit/db0aafdc7766048c28597d37f31977ac7833a62e#diff-7f0d18a324c74248aefb49bf1aabe8ca

`CreateContact` component should be defined using Functional Stateless Component syntax.  
`CreateContact` component is currently defined as a class based Component, but it holds no state and only has a render() method.  

According to this course's earlier lessons, it  was recommended that we use Stateless Functional Components, if the component needs no `state`, and only uses a Component's `render` method.  

My understanding is that it should be refactored to a class based Component (with State) only when necessary.  

I was able to complete the lesson with no issues, with it as a Stateless Functional Component.

Not a "bug" per say, but it does conflict with best practices of the teachings.

Instruction, by the way is Excellent.  Course is Nearly Perfect ! - True Pro's as Instructors :-)

**Comment by hbkwong** [comment]
Hey Sheryl! Thanks for your detailed report on this one. Since the component doesn't have state (and doesn't need any lifecycle methods), it can absolutely be written as a stateless functional component.

It's not a bug like you mentioned, but consistency is important, after all. We're making updates to the React Nanodegree program, so I'll mark this as something to review for the future release.
