### ISSUE TITLE
Lesson 2.4 - 2nd Video clarification

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#23]
Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/82766b2b-1870-4904-aa90-8ccbe63928c5/lessons/7f45040c-7d92-476d-8ad4-36853d6aa111/concepts/7e923430-f20c-4d6e-a328-2190b68b6ffe

It isn't clear if you are supposed to follow along and add the code shown in the second video to your recently created create-react-app project. The main issue is that the second video doesn't tell or show you what file to put the ContactList component in. For those new to React, it could be confusing if they want to follow along.

It would be helpful if you could put some text above the video and let the student know if you want them to follow along and add the code to their create-react-app project, and also what file is being updated.

Also, the instructor is pasting the code for ContactList, but the student is not asked to write or save the code for ContactList in the previous video where that component is created, so if the student is to follow along, maybe include the code for ContactList above the video for them to copy and paste themselves as it is not shown in the video for very long.

**Comment by kellim** [comment]
After starting lesson 3, it is clear you don't need to add the code from this video to your create-react-app project, so it would be helpful if there was text above the video noting that, since when you watch the video you might think you need to pause the video and copy the code.

**Comment by richardkalehoff** [comment]
We now link to a repo that includes changes for every video. I've added a link beneath the screencast you're talking about to the commit on GitHub. This commit shows all of the changes that the student should have made. Even though it's not necessary for the student to add the code (since we're deleting it in the next section), it's helpful to follow along to get hands-on experience. Thanks for all of your awesome feedback kellim! It's been super helpful!
