### ISSUE TITLE
MyReads - can't use JSX

### ISSUE THREAD

**Issue by kellim** [udacity/reactnd-issues#58]
Can you please clarify for students somewhere that project submissions should not include .jsx files, because they do not show up in the code review system.

Link: https://classroom.udacity.com/nanodegrees/nd019beta/parts/2ce35acc-f3fe-47b0-aea1-56793162efaf/modules/1c3110e6-46f7-4929-8cf4-8332afbbaadf/lessons/5d31386c-8c1c-4f32-974d-6bf3c1062cba/concepts/e7df4589-29d8-4d49-b760-a1db72d6cbdb

**Comment by kellim** [comment]
To clarify, you can use jsx in the project, but you can't name files with the .jsx extension.

**Comment by hbkwong** [comment]
Thanks for the catch, Kelli! I haven't seen too many submissions with the `.jsx` extension (probably just one or two, really), but I do agree that it's something we can clarify. The change has since been made in the Submission Requirements section!

@richardkalehoff, I wasn't able to update the Project Instructions script (currently, view-only), but the clarification was added in CoCo.
