### ISSUE TITLE
Semicolons use - Style Guide

### ISSUE THREAD

**Issue by itamarborges** [udacity/reactnd-issues#67]
According to JavaScript Style Guide, we must "Always use semicolons.". But throughout the course and in the templates code, the guys aren't using semicolons at all. Which rule are we supposed to follow?

**Comment by itamarborges** [comment]
http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html

**Comment by hbkwong** [comment]
itamarborges,

Totally hear you on this one. Personally speaking, when learning JavaScript myself, semicolons were a requirement to end expressions -- no questions about it. I still stand by this, but I also stand by _consistency_, which is what our team decided to practice in the screencasts and code snippets you see through the curriculum.

Since we're transpiling our app with Babel, it's true that semicolons may be omitted without any major adverse consequences. To be frank though, if I were to create this all from the ground-up, I would always use semicolons where appropriate.

This post shares some perspective: https://medium.com/@kentcdodds/semicolons-in-javascript-a-preference-dd8fc8b80895

Feel free to Slack me if you have further comments to share.
