### ISSUE TITLE
Lesson 1.4 Question 2 of 2 - Question not clear for which components are receiving inputs from the user. May cause confusion

### ISSUE THREAD

**Issue by GabrielAmazonas** [udacity/reactnd-issues#77]

**Comment by hbkwong** [comment]
Hi GabrielAmazonas,

Thanks for reaching out! FlightPlanner and LocationPicker should be the only components in charge of making updates, since they're the only components that have nested child components.

If you think the question should be phrased differently, let me know! Always open to suggestions/updates. Feel free to shoot me a Slack message too!

**Comment by hbkwong** [comment]
Closing this for now. Feel free to Slack me (or open up a new issue) if you run into any difficulty later on too!
