### ISSUE TITLE
keyword let somehow used as a variable name

### ISSUE THREAD

**Issue by rscharfer** [udacity/reactnd-issues#99]

**Comment by rscharfer** [comment]
https://youtu.be/1mUHwzpgjwQ   ....   shortly after the 50 second mark in this video, Tyler somehow uses 'let' as a variable name, probably by accident, but in some js environments, you can do that. its the second video in lesson 1 of redux - pure functions...

**Comment by rscharfer** [comment]
![let.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5976d7d6322ccf001a1cd5bb/125516c66e82c728ace21e0d46e4918e61cec1b99de6b546a749b2ce6b137e277154a62a7281ba2eed1429515f0949a5445a5a40f5eb9539e4e76224d50152a7842f4d7ed43f17a6b9871fbe08b827824b81b4b9895e8d.PNG)

**Comment by hbkwong** [comment]
Hey @rscharfer, it looks like two global variables were created. Not a big deal in the console (especially since `friends` is the variable being used), and it doesn't affect the rest of the example, but I would not advise this in any development code. I'll keep on the lookout in the Slack community to make sure this doesn't become an issue. Thanks for reaching out!
